<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="ESICDRLAPTOP020" name="com.qa.tests.CaseSheetTest" tests="6" failures="0" timestamp="13 Jan 2021 07:56:22 GMT" time="15.049" errors="1">
  <testcase name="doLoginTest" time="0.840" classname="com.qa.tests.CaseSheetTest"/>
  <testcase name="doNavigateToSelectHospitalLocationTest" time="1.719" classname="com.qa.tests.CaseSheetTest"/>
  <testcase name="doNavigateToHISHomeTest" time="2.231" classname="com.qa.tests.CaseSheetTest"/>
  <testcase name="doNavigateToPatientCheckInTest" time="0.716" classname="com.qa.tests.CaseSheetTest"/>
  <testcase name="doPatientCheckINTest" time="8.571" classname="com.qa.tests.CaseSheetTest"/>
  <testcase name="doCaseSheetPrecription" time="0.972" classname="com.qa.tests.CaseSheetTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.qa.tests.CaseSheetTest.doCaseSheetPrecription(CaseSheetTest.java:67)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- doCaseSheetPrecription -->
</testsuite> <!-- com.qa.tests.CaseSheetTest -->
